### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by manwooo** [ParkSangGwon/TedPermission#143]
How to solve this error ? this error is not always,..

manifest.xml include permission..
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

i'm using below version.
implementation 'gun0912.ted:tedpermission:2.2.3'

bleow is  stack trace... 

java.lang.RuntimeException: Unable to start activity ComponentInfo{kr.co.nexict.next/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.app.Activity.getFilesDir()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.app.Activity.getFilesDir()' on a null object reference
	at i.a.a.c.j0.e.a.a(:103)
	at com.gun0912.tedpermission.TedPermissionActivity.B(Unknown Source:45)
	at com.gun0912.tedpermission.TedPermissionActivity.z(Unknown Source:48)
	at com.gun0912.tedpermission.TedPermissionActivity.onCreate(:7)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	... 12 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.app.Activity.getFilesDir()' on a null object reference
	at i.a.a.c.j0.e.a.a(:103)
	at com.gun0912.tedpermission.TedPermissionActivity.B(Unknown Source:45)
	at com.gun0912.tedpermission.TedPermissionActivity.z(Unknown Source:48)
	at com.gun0912.tedpermission.TedPermissionActivity.onCreate(:7)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by ted-prnd** [comment]
Do you have problem scenario?
