### ISSUE TITLE
AppCompat Theme issue...

### ISSUE THREAD

**Issue by cking24343** [ParkSangGwon/TedPermission#2]
I have a hello world activity that I dropped this lib in to try it out. I'm getting an issue for AppCompatTheme, see log here:

FATAL EXCEPTION: main
Process: sample.sample_mpermissions, PID: 7863
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{sample.sample_mpermissions/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:331)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.onPostCreate(AppCompatDelegateImplV7.java:164)
                                                     at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:87)
                                                     at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1188)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2398)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

I already have them in manifest (android:theme="@style/AppTheme") thats using my theme from my styles XML: 

`
 
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>`

Thoughts on what to try?

**Comment by ParkSangGwon** [comment]
do you use AppCompat theme?

**Comment by cking24343** [comment]
Yes. If you look at the first comment I posted you can see the style that the sample app I made to test this lib with was already using Theme.AppCompat. With that being said I am using the Light.DarkActionBar extension as well, but this shouldnt be an issue, should it?

**Comment by ParkSangGwon** [comment]
@cking24343 did you clone(or download) demo project and test it?
Let compare your project and demo project

**Comment by ParkSangGwon** [comment]
No anwer. Closed
