### ISSUE TITLE
Could not dispatch event

### ISSUE THREAD

**Issue by devLibCH** [ParkSangGwon/TedPermission#28]
TedPermission을 적용한 앱을 런칭중에 있습니다.
사용자 uuid 생성을 위해 READ_PHONE_STATE 퍼미션을 받는 중에 다음과 같은 Exception이 발생했습니다.
proguard는 사용하고있지 않습니다.

` java.lang.RuntimeException: Could not dispatch event: class com.gun0912.tedpermission.busevent.TedPermissionEvent to handler [EventHandler public void com.gun0912.tedpermission.TedInstance.onPermissionResult(com.gun0912.tedpermission.busevent.TedPermissionEvent)]: getDeviceId: Neither user 10232 nor current process has android.permission.READ_PHONE_STATE.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

`Caused by java.lang.RuntimeException: Could not dispatch event: class com.gun0912.tedpermission.busevent.TedPermissionEvent to handler [EventHandler public void com.gun0912.tedpermission.TedInstance.onPermissionResult(com.gun0912.tedpermission.busevent.TedPermissionEvent)]: getDeviceId: Neither user 10232 nor current process has android.permission.READ_PHONE_STATE.
       at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
       at com.squareup.otto.Bus.dispatch(Bus.java:387)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at com.squareup.otto.Bus.post(Bus.java:337)
       at com.gun0912.tedpermission.busevent.TedBusProvider.post(TedBusProvider.java:49)
       at com.gun0912.tedpermission.TedPermissionActivity.permissionGranted(TedPermissionActivity.java:115)
       at com.gun0912.tedpermission.TedPermissionActivity.onRequestPermissionsResult(TedPermissionActivity.java:208)
       at android.app.Activity.requestPermissions(Activity.java:4163)
       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:45)
       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:375)
       at com.gun0912.tedpermission.TedPermissionActivity.requestPermissions(TedPermissionActivity.java:184)
       at com.gun0912.tedpermission.TedPermissionActivity.checkPermissions(TedPermissionActivity.java:175)
       at com.gun0912.tedpermission.TedPermissionActivity.onCreate(TedPermissionActivity.java:58)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by ysnows** [comment]
i encounter this problem in android 7.1 platform

**Comment by ParkSangGwon** [comment]
@devLibCH 
android.permission.READ_PHONE_STATE 권한을 요청하셨나요?
TedPermission을 사용하는 소스코드를 올려주시면 좋을것 같습니다.

**Comment by ParkSangGwon** [comment]
No answer.
