### ISSUE TITLE
onCreate 에서 사용할 때...

### ISSUE THREAD

**Issue by e2com** [ParkSangGwon/TedPermission#32]
안녕하세요... 
마시멜로 에서 권한 문제 때문에 고민을 하다가... 구글링을 통해서 알게 되어 ... 잘 사용하고 있습니다. 
감사드립니다. 

궁금한 부분은

1. onCreate 에서 권한이 필요한 부분이 아래 부분에 있는데... 잘 체크가 되지 않는 경우가 간혹 있는 것 같습니다. 

2. onCreate 에서 Service 을 실행시켰는데... 해당 서비스에서 권한이 필요한 경우 체크가 잘 될까요?

이런 경우가 있었는지 알려 주시면 도움이 될 것 같습니다.  Thank You!!! 감사드려요...

**Comment by ParkSangGwon** [comment]
@e2com 

1. 잘체크가 되지않는경우가 정확히 어떤경우인가요? 소스코드가 있다면 올려주세요
2. 서비스에서 권한획득이 가능하다고해도 서비스를 돌리기전에 앱안에서 미리 사용자에게 충분히 설명을 하고 권한을 획득하고서 서비스에서 돌리는게 좋을것 같습니다.

**Comment by e2com** [comment]
답변 감사 드려요... 아래 source 같이 사용을 하고자 하는데... 앱을 삭제 하고 다시 설치를 진행하게 되는 경우 tMgr.getLine1Number(); 요 부분에 권한 문제 때문에 Exception 이 발생 합니다. 
왜 그럴까요???  제가 뭘 잘못 하고 있나요???

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        PermissionListener permissionlistener = new PermissionListener() {
            @Override
            public void onPermissionGranted() {

            }

            @Override
            public void onPermissionDenied(ArrayList<String> deniedPermissions) {
                new AlertDialog.Builder(Main.this)
                        .setTitle(R.string.app_name_kr)
                        .setMessage(Html.fromHtml( getStringID(R.string.label_permission_denied) + "\n" + deniedPermissions.toString() ))
                        .setIcon(R.drawable.soo).setCancelable(false)
                        .setNegativeButton(getStringID(R.string.label_close), null).show();

                finish();
            }

        };

        new TedPermission(this)
                .setPermissionListener(permissionlistener)
                .setRationaleConfirmText("setRationaleConfirmText()")
                .setDeniedCloseButtonText("setDeniedCloseButtonText()")
                .setGotoSettingButton(true)
                .setGotoSettingButtonText("setGotoSettingButtonText()")
                .setDeniedMessage(getStringID(R.string.mesg_permission_agree1) + "\n\n" + getStringID(R.string.mesg_permission_agree2))
                .setPermissions(Manifest.permission.WRITE_EXTERNAL_STORAGE
                              , Manifest.permission.ACCESS_FINE_LOCATION
                        , Manifest.permission.READ_CALENDAR
                        , Manifest.permission.WRITE_CALENDAR
                        , Manifest.permission.READ_CONTACTS
                        , Manifest.permission.ACCESS_FINE_LOCATION
                        , Manifest.permission.ACCESS_COARSE_LOCATION
                        , Manifest.permission.SEND_SMS
                        , Manifest.permission.RECEIVE_SMS
                        , Manifest.permission.READ_SMS
                        , Manifest.permission.READ_CALL_LOG
                        , Manifest.permission.WRITE_CALL_LOG
                        , Manifest.permission.RECEIVE_MMS
                        , Manifest.permission.READ_PHONE_STATE)
                .check();


        mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);

        // 뒤로가기 버튼 처리를 위해서
        backPressCloseHandler = new BackPressCloseHandler(this);

        timeThread();
        // ATTENTION: This "addApi(AppIndex.API)"was auto-generated to implement the App Indexing API.
        // See https://g.co/AppIndexing/AndroidStudio for more information.
        mGoogleApiClient = new GoogleApiClient.Builder(this)
                .addConnectionCallbacks(this)
                .addOnConnectionFailedListener(this)
                .addApi(LocationServices.API)
                .addApi(AppIndex.API).build();

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.addDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);

        tMgr = (TelephonyManager) this.getSystemService(Context.TELEPHONY_SERVICE);
        if(checkSelfPermission(Manifest.permission.READ_SMS) != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(new String[]{Manifest.permission.READ_SMS },
                    MY_PERMISSION_REQUEST_STORAGE);
        } else {
            AllConfig.PHONE_NUMBER = tMgr.getLine1Number();
        }
        

    }

**Comment by e2com** [comment]
앱에 부여된 권한을 다 제거 하고 다시 실행하면 아래 처럼 .getLine1Number 실행시에 권한에 대한 오류가 발생 됩니다.  예상 하기 로는 앞에서 권한을 점검해서 권한을 부여 받아서 실행이 되어야 할 것 같은데...  다른 조치를 어떻게 해야 할까요???

2-22 21:27:57.154 18180-18180/com.nari.mprc E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.nari.mprc, PID: 18180
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nari.mprc/com.nari.mprc.Main}: java.lang.SecurityException: getLine1NumberForDisplay: Neither user 10466 nor current process has android.permission.READ_SMS.
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:158)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                Caused by: java.lang.SecurityException: getLine1NumberForDisplay: Neither user 10466 nor current process has android.permission.READ_SMS.
                                                                   at android.os.Parcel.readException(Parcel.java:1620)
                                                                   at android.os.Parcel.readException(Parcel.java:1573)
                                                                   at com.android.internal.telephony.ITelephony$Stub$Proxy.getLine1NumberForDisplay(ITelephony.java:4882)
                                                                   at android.telephony.TelephonyManager.getLine1NumberForSubscriber(TelephonyManager.java:2447)
                                                                   at android.telephony.TelephonyManager.getLine1Number(TelephonyManager.java:2425)
                                                                   at com.nari.mprc.Main.onCreate(Main.java:427)

**Comment by gkduduu** [comment]
READ_SMS 권한이 필요한 부분은 PermissionListener 내의 onPermissionGranted(권한 획득) 이 완료된 이후 실행되어져야 합니다. 해당 코드는 권한 획득 도중 실행되어지기 때문에 runtime exception이 발생하는 것으로 보입니다.

**Comment by e2com** [comment]
답변 감사 드려요. 
그럼 앱에서 필요한 권한 획득을 먼저 하고 진행을 하려면... onPermissionGranted 안에서 그 다음 action 을 다 넘으면 되겠네요...

**Comment by ParkSangGwon** [comment]
@e2com 네 @gkduduu 님의 말씀처럼 권한획득후에 할 작업은 `onPermissionGranted()` 안에서 이루어져야 합니다.
저 코드대로 한다면 권한획득이 이루어지든 말든 다음코드는 진행이 되어버리니까요
그부분을 수정하시면 바로 해결되실겁니다.
