### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by venkat20390** [ParkSangGwon/TedPermission#35]
Hi, 

I am seeing an app crash which is related to TedPermission library. I could see the following stack traces in my bug tracking system which occurs in Samsung devices like samsung SM-J700F, samsung SM-N910C, samsung SM-J710F, samsung SM-J700H, samsung SM-G900F, samsung SM-G935F, samsung SM-A500F, samsung SM-J500H which runs on 6.0.1.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miragestacks.thirdeye/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.NullPointerException: Attempt to get length of null array
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.gun0912.tedpermission.TedPermissionActivity.void checkPermissions(boolean)(SourceFile:127)
	at com.gun0912.tedpermission.TedPermissionActivity.void onCreate(android.os.Bundle)(SourceFile:57)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
	... 9 more

**Comment by ParkSangGwon** [comment]
@venkat20390 Did you set permissions list like ` .setPermissions(Manifest.permission.READ_CONTACTS, Manifest.permission.ACCESS_FINE_LOCATION)` ?
