### ISSUE TITLE
com.jfrog.bintray 오류가 발생됩니다.

### ISSUE THREAD

**Issue by caludas** [ParkSangGwon/TedPermission#38]
수고 많으십니다
오류 로그 전문입니다.

Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'com.jfrog.bintray' not found.
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:110)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
	at org.gradle.groovy.scripts.DefaultScript.apply(DefaultScript.java:109)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at bintrayv1_76e1dnwmf4o7tzwnw7d93bcjx.run(https://raw.githubusercontent.com/nuuneoi/JCenter/master/bintrayv1.gradle:1)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)

**Comment by ParkSangGwon** [comment]
@caludas 
예제 프로젝트 다운받아서 돌려보실때 발생한 오류이실겁니다.
build.gradle에 plugin이 없어서 생긴 오류였는데요.
다시 pull 받아보시면 오류없이 사용가능하실 겁니다.
