### ISSUE TITLE
AppCompat 에러 질문입니다.

### ISSUE THREAD

**Issue by JeongJinyong** [ParkSangGwon/TedPermission#43]
04-04 17:21:04.546 18876-18990 E/ACRA: com.cocoa_studio.doznut fatal error : Unable to start activity ComponentInfo{com.cocoa_studio.doznut/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cocoa_studio.doznut/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                           at android.os.Looper.loop(Looper.java:148)
                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                           at java.lang.reflect.Method.invoke(Native Method)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                        Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                           at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:351)
                                           at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:320)
                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:281)
                                           at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
                                           at android.support.v7.app.AlertController.installContent(AlertController.java:214)
                                           at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:258)
                                           at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                           at android.app.Dialog.show(Dialog.java:295)
                                           at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:956)
                                           at com.gun0912.tedpermission.TedPermissionActivity.showRationaleDialog(TedPermissionActivity.java:251)
                                           at com.gun0912.tedpermission.TedPermissionActivity.checkPermissions(TedPermissionActivity.java:196)
                                           at com.gun0912.tedpermission.TedPermissionActivity.onCreate(TedPermissionActivity.java:65)
                                           at android.app.Activity.performCreate(Activity.java:6251)
                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                           at android.os.Looper.loop(Looper.java:148) 
                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                           at java.lang.reflect.Method.invoke(Native Method) 
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

보면 오히려 테드퍼미션에서 다이얼로그를 생성할때 에러가 나던데
이유가 뭔지 알 수 있을까요??
우선 최대한 비슷한 환경을 만들기 위해서 테스트앱에 있는
앱테마를 가져다가 사용했습니다.
그런데 제앱에서는 저런에러가 나네요 ㅠㅠ

**Comment by ParkSangGwon** [comment]
@JeongJinyong 현재 해당 앱에서 사용중인 Theme가 어떤건가요?

**Comment by ParkSangGwon** [comment]
현재 사용중이신 버전이 아래와 같이 설정되어있는지 확인하시기 바랍니다
dependencies {
    compile 'gun0912.ted:tedpermission:1.0.3'
}
