### ISSUE TITLE
NotFoundException 

### ISSUE THREAD

**Issue by Mahmudul531** [ParkSangGwon/TedPermission#54]
Please help me. 
FYI - I've added produgard into apps.
```

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=10, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }} to activity {mdirectory.secapps.com.mdirectory/com.gun0912.tedpermission.TedPermissionActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5007)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
	at android.app.ActivityThread.access$1600(ActivityThread.java:230)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7409)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.Resources.getValue(Resources.java:2598)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:4431)
	at android.content.res.Resources.getLayout(Resources.java:2412)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
	at android.support.v7.app.y.b(SourceFile:292)
	at android.support.v7.app.ah.setContentView(SourceFile:83)
	at android.support.v7.app.AlertController.a(SourceFile:225)
	at android.support.v7.app.n.onCreate(SourceFile:257)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:733)
	at android.app.Dialog.show(Dialog.java:469)
	at android.support.v7.app.n$a.c(SourceFile:955)
	at com.gun0912.tedpermission.TedPermissionActivity.showPermissionDenyDialog(SourceFile:270)
	at com.gun0912.tedpermission.TedPermissionActivity.onRequestPermissionsResult(SourceFile:197)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)
	at android.app.Activity.dispatchActivityResult(Activity.java:7169)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5003)
	... 9 more
```

**Comment by ParkSangGwon** [comment]
@Mahmudul531 Show me your proguard contents

**Comment by Mahmudul531** [comment]
Here , please check 
```

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in G:\Andoid_sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
-keepclassmembers class com.datehailgmail.mdirectory.WebViewShowContent {
   public *;
}

-keep class org.apache.lucene.** { *; }
-keep class com.gun0912.tedpermission.** { *; }
-keepattributes EnclosingMethod
-keepattributes InnerClasses

-keepattributes *Annotation*
-keepclassmembers class ** {
    @com.squareup.otto.Subscribe public *;
    @com.squareup.otto.Produce public *;
}

-keep class com.canelmas.let.** { *; }
-keepnames class * implements com.canelmas.let.RuntimePermissionListener

-keepclassmembers class * implements com.canelmas.let.RuntimePermissionListener {
    public void onRequestPermissionsResult(***);
}

-keepclasseswithmembernames class * {
    @com.canelmas.let.* <methods>;
}
```

**Comment by ParkSangGwon** [comment]
Please update version and read `Readme`
```java
dependencies {
    compile 'gun0912.ted:tedpermission:2.0.0'
}
```
