### ISSUE TITLE
 AppCompat Theme issue... #2 

### ISSUE THREAD

**Issue by cking24343** [ParkSangGwon/TedPermission#6]
Sorry for belated response to this. I haven't had time to circle back to this until today. I've uploaded my sample to google drive ( https://drive.google.com/folderview?id=0B5qQYhAfSI7kUy1KekI3aVRsc0E&usp=sharing ) so you can pull it down and run it. I still get the error:

03-27 13:00:02.351 29449-29449/dataforensics.sample_mpermissions E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: dataforensics.sample_mpermissions, PID: 29449
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{dataforensics.sample_mpermissions/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                    Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:331)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.onPostCreate(AppCompatDelegateImplV7.java:164)
                                                                                       at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:87)
                                                                                       at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1188)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2398)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by cking24343** [comment]
![ted issues](https://cloud.githubusercontent.com/assets/4295331/14066658/643aedd4-f41d-11e5-86a7-a8b9b7bb32e2.png)

**Comment by cking24343** [comment]
Any update on this issue?

**Comment by sirvon** [comment]
@cking24343 did you solve this?
@ParkSangGwon this problem won't go away....can you help us?

thanks!

**Comment by cking24343** [comment]
@sirvon no resolution yet, I am using Dexter (https://github.com/Karumi/Dexter) at the moment...

**Comment by anupamchugh** [comment]
Stuck with the same issue. Is it resolved?

**Comment by cking24343** [comment]
Over a yr no resolution, have since moved onto Dexter (https://github.com/Karumi/Dexter), been using it over a yr now with no issues.

**Comment by ted-hpcnt** [comment]
@cking24343 I checked your project.
That project use old version
change library version like this.
```javascript
dependencies {
    compile 'gun0912.ted:tedpermission:1.0.3'
}
```

Don't need jitpack()

@sirvon @anupamchugh

**Comment by ParkSangGwon** [comment]
@cking24343 I checked your project.
That project use old version
change library version like this.

dependencies {
    compile 'gun0912.ted:tedpermission:1.0.3'
}
Don't need jitpack()

@sirvon @anupamchugh

**Comment by ParkSangGwon** [comment]
Now, Dialog use specific theme
Please update version
```java
dependencies {
    compile 'gun0912.ted:tedpermission:2.0.0'
}
```
