### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by KKKimyh** [ParkSangGwon/TedPermission#62]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.gun0912.tedpermission.PermissionListener.onPermissionDenied(java.util.ArrayList)' on a null object reference
                                                                   at com.gun0912.tedpermission.TedPermissionActivity.permissionResult(TedPermissionActivity.java:138)
                                                                   at com.gun0912.tedpermission.TedPermissionActivity.access$000(TedPermissionActivity.java:25)
                                                                   at com.gun0912.tedpermission.TedPermissionActivity$3.onClick(TedPermissionActivity.java:277)
                                                                   at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by JSpiner** [comment]
it looks same with #59

**Comment by ParkSangGwon** [comment]
@KKKimyh @JSpiner 
This error solved at `v2.1.0`
Please update library version.
