### ISSUE TITLE
Issue with only OS 8 (Android)

### ISSUE THREAD

**Issue by socialvanana** [ParkSangGwon/TedPermission#70]
I'm using 2.1.0(tedpermission)

Below is crash log.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abletree.someday/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3013)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6887)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1370)
Caused by java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
       at android.app.Activity.onCreate(Activity.java:1037)
       at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:297)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
       at com.gun0912.tedpermission.TedPermissionActivity.onCreate(TedPermissionActivity.java:69)
       at android.app.Activity.performCreate(Activity.java:7173)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2891)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3013)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6887)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1370)

**Comment by socialvanana** [comment]
#63 (Duplicate)
